### ISSUE TITLE
node-red stops when using voice2json

### ISSUE THREAD

**Issue by shiddugmail** [johanneskropf/node-red-contrib-voice2json#4]
**Environment:**
Node-RED version: v1.0.2
Node.js  version: v12.2.0
Windows 10.0.17134 x64 LE

**Log of node-red**
9 Sep 12:35:15 - [metric] {"level":99,"nodeid":"9662584f.e60268","event":"node.ui_microphone.send","msgid":"d2f91ac.0029de8","timestamp":1599635115148}
9 Sep 12:35:15 - [metric] {"level":99,"nodeid":"5800564.84d06a8","event":"node.voice2json-transcribe-stream.receive","msgid":"d2f91ac.0029de8","timestamp":1599635115149}
9 Sep 12:35:15 - [red] Uncaught Exception:
9 Sep 12:35:15 - Error: spawn voice2json ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

I am really interested to explore this. Your response to resolve this would save lot of time. 

Thank you,
Regards,
Shiddu

**Comment by johanneskropf** [comment]
Both voice2json and node-red-contrib-voice2json will only work on **linux** as is it also states in the first paragraph of the documentation. You could try running both inside the linux subsystem for windows but I have no experience with that.
Johannes

**Comment by shiddugmail** [comment]
hello @johanneskropf 

Thank you for response. I tried in linux Ubuntu, i get the same issue. May be I am doing something wrong. 
Your help will resolve it. 

Regards,
Shiddu

**Comment by shiddugmail** [comment]
@johanneskropf Can you please help.

**Comment by johanneskropf** [comment]
Sorry for the long wait unfortunately I have been very busy. Can you run voice2json from the commandline on the system that both nodered and voice2json are installed on?
