### ISSUE TITLE
Tutorial: Missing "living room lamp" in grammar example

### ISSUE THREAD

**Issue by DDDanny** [johanneskropf/node-red-contrib-voice2json#6]
**Classification**: minor

**Context**:
[https://github.com/johanneskropf/node-red-contrib-voice2json/wiki/Getting-started---Step-by-step-tutorial](https://github.com/johanneskropf/node-red-contrib-voice2json/wiki/Getting-started---Step-by-step-tutorial)
at Chapter 9. The TTI (text-to-intent) recognition

**Issue**:
`turn [the] ( | garage light) {name} (on | off) {state}`
`            ^-missing: living room lamp `

**Expected content**:
`turn [the] (living room lamp | garage light) {name} (on | off) {state}`

**Comment by johanneskropf** [comment]
Fixed
